scf4:
	alacritty --hold --command python main.py --headless

scf5:
	alacritty --hold --command python main.py

scf6:
	# alacritty --hold --command cat pdfbuild/generated.csv
	# alacritty --command sc-im pdfbuild/generated.csv
	alacritty --hold --command python pdf.py && cat pdfbuild/generated.csv
	# alacritty --hold --command python pdf.py
